USE [AceleraPlenoDB]
GO
/****** Object:  Table [dbo].[TBOPERACAO]    Script Date: 27/02/2024 10:16:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBOPERACAO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CODTIPOTERMINAL] [int] NOT NULL,
	[CODOPERACAO] [nvarchar](10) NOT NULL,
	[DESCOPERACAO] [nvarchar](100) NOT NULL,
	[CODHISTORICO] [int] NOT NULL,
	[DESCHISTORICO] [nvarchar](100) NOT NULL,
	[DATAOPERACAO] [datetime2](7) NOT NULL,
	[CODTERMINAL] [nvarchar](50) NULL,
	[PA] [int] NULL,
	[CODAUT] [nvarchar](10) NULL,
	[VALOR] [money] NOT NULL,
	[DATAHORACARGA] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBTERMINAL]    Script Date: 27/02/2024 10:16:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBTERMINAL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDINSTITUICAO] [int] NOT NULL,
	[IDPRODUTO] [int] NOT NULL,
	[IDUNIDADEINST] [int] NOT NULL,
	[DATAPROCESSAMENTO] [datetime2](7) NOT NULL,
	[NUMTERMINAL] [int] NOT NULL,
	[IDTIPOTERMINAL] [int] NOT NULL,
	[IDSITUACAOTERMINAL] [int] NOT NULL,
	[IDUSUARIO] [nvarchar](100) NOT NULL,
	[IDUSUARIOLIBERACAO] [nvarchar](100) NOT NULL,
	[DESCESTTRABALHO] [nvarchar](50) NULL,
	[NUMULTAUTENTICACAO] [int] NOT NULL,
	[NUMLOTECCO] [int] NOT NULL,
	[MENORVALORNOTA] [numeric](18, 4) NOT NULL,
	[DATAHORALIBERACAO] [datetime2](7) NOT NULL,
	[NUMLOTECHEQUE] [int] NOT NULL,
	[NUMULTSEQLANCCCO] [int] NOT NULL,
	[NUMULTREMESSA] [int] NOT NULL,
	[IDCLIENTECOR] [int] NULL,
	[NUMLOTEDOC] [int] NOT NULL,
	[NUMULTSEQDOC] [int] NOT NULL,
	[DESCVERSAOSO] [nvarchar](200) NULL,
	[DESCMEMORIARAM] [nvarchar](50) NULL,
	[DESCESPACODISCO] [nvarchar](50) NULL,
	[DESCPACOTESERVICO] [nvarchar](50) NULL,
	[NUMLOTEDEC] [int] NOT NULL,
	[NUMULTSEQDEC] [int] NOT NULL,
	[VALORLIMITESAQUE] [numeric](18, 4) NOT NULL,
	[VALORLIMITETERMINAL] [numeric](18, 4) NOT NULL,
	[NUMTESOUREIRO] [int] NULL,
	[NUMIPTESOUREIRO] [nvarchar](50) NULL,
	[CODTIPOBALANCEAMENTO] [int] NULL,
	[NUMTIMEOUTDISPENSADOR] [int] NULL,
	[CODLADODEPOSITARIO] [int] NULL,
	[NUMPORTATESOUREIRO] [int] NULL,
	[NUMCHEKALTERACAO] [int] NULL,
	[DATAHORACARGA] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBTIPOOPERACAO]    Script Date: 27/02/2024 10:16:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBTIPOOPERACAO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDGRUPOCAIXA] [int] NOT NULL,
	[IDOPERACAOCAIXA] [int] NOT NULL,
	[CODOPERACAO] [nvarchar](10) NOT NULL,
	[DESCOPERACAO] [nvarchar](100) NOT NULL,
	[CODHISTORICO] [int] NOT NULL,
	[DESCHISTORICO] [nvarchar](100) NOT NULL,
	[SENSIBILIZACAO] [nchar](1) NOT NULL,
	[DATAHORACARGA] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBTIPOTERMINAL]    Script Date: 27/02/2024 10:16:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBTIPOTERMINAL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CODTIPOTERMINAL] [int] NOT NULL,
	[DESCTIPOTERMINAL] [nvarchar](100) NOT NULL,
	[BOLACESSOLIBERADO] [int] NOT NULL,
	[NUMCHEKALTERACAO] [int] NOT NULL,
	[PA] [int] NOT NULL,
	[LIMSUPERIOR] [int] NOT NULL,
	[LIMINFERIOR] [int] NOT NULL,
	[DATAHORACARGA] [datetime2](7) NOT NULL,
 CONSTRAINT [PK__TBTIPOTE__3214EC2791F4FF79] PRIMARY KEY CLUSTERED 
(
	[CODTIPOTERMINAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBTRANSPORTADORAVALORES]    Script Date: 27/02/2024 10:16:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBTRANSPORTADORAVALORES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NUMCNPJ] [nvarchar](50) NOT NULL,
	[DESCTRANSPORTADORA] [nvarchar](100) NOT NULL,
	[PA] [int] NOT NULL,
	[DATAHORACARGA] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBUNIDADEINSTITUICAO]    Script Date: 27/02/2024 10:16:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBUNIDADEINSTITUICAO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDINSTITUICAO] [int] NOT NULL,
	[IDUNIDADEINST] [int] NOT NULL,
	[NUMCNPJ] [nvarchar](20) NULL,
	[NOMEUNIDADE] [nvarchar](200) NOT NULL,
	[SIGLAUNIDADE] [nvarchar](50) NOT NULL,
	[DATACADASTRAMENTO] [datetime] NOT NULL,
	[CODTIPOINSTITUICAO] [int] NOT NULL,
	[CODTIPOUNIDADE] [int] NOT NULL,
	[DATAINICIOSICOOB] [datetime] NULL,
	[DATAFIMSICOOB] [datetime] NULL,
	[DATAHORACARGA] [datetime] NOT NULL,
	[NUMCHECKALTERACAO] [int] NOT NULL,
	[IDUNIDADEINSTRESP] [int] NULL,
	[CODSITUACAOUNID] [int] NOT NULL,
	[NUMSIRC] [int] NULL,
	[DESCENDINTERNET] [nvarchar](100) NULL,
	[DATAINICIOUTILIZACAOMARCASICOOB] [datetime] NULL,
	[BOLATENDIMENTOPUBLICOEXTERNO] [int] NULL,
	[NUMINSCRICAOMUNICIPAL] [int] NULL,
	[NUMNIRE] [int] NULL,
	[IDINSTITUICAOINCORPORADORA] [int] NULL,
	[DATAINCORPORACAO] [datetime] NULL,
	[BOLUTILIZACOMPARTILHAMENTO] [int] NULL,
	[DATAINICIOFUNCIONAMENTO] [datetime] NULL,
	[DATAFIMFUNCIONAMENTO] [datetime] NULL,
	[BOLUTILIZASISBR] [int] NOT NULL,
	[DATAINICIOUTILIZASISBR] [datetime] NULL,
	[DATAFIMUTILIZASISBR] [datetime] NULL,
	[BOLISENTOINSCRICAOMUNICIPAL] [int] NULL,
	[BOLISENTONIRE] [int] NULL,
	[BOLSINALIZADOSICOOB] [int] NULL,
	[BOLPAINCORPORADO] [int] NULL,
 CONSTRAINT [PK__TBUNIDAD__3214EC2794B13B19] PRIMARY KEY CLUSTERED 
(
	[IDUNIDADEINST] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBUSUARIO]    Script Date: 27/02/2024 10:16:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBUSUARIO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDINSTITUICAO] [int] NOT NULL,
	[DATAHORACARGA] [datetime] NOT NULL,
	[NUMCHECKALTERACAO] [int] NOT NULL,
	[IDUSUARIO] [nvarchar](100) NOT NULL,
	[IDINSTITUICAOUSUARIO] [int] NOT NULL,
	[IDUNIDADEINSTUSUARIO] [int] NOT NULL,
	[DESCNOMEUSUARIO] [nvarchar](200) NULL,
	[BOLHABILITADOUSUARIO] [int] NOT NULL,
	[DESCSTATUSUSUARIO] [nvarchar](50) NULL,
	[BOLVERIFICANOMEMAQUINA] [int] NOT NULL,
	[DESCEMAIL] [nvarchar](100) NULL,
 CONSTRAINT [PK__TBUSUARI__3214EC27C0637613] PRIMARY KEY CLUSTERED 
(
	[IDUSUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TBOPERACAO]  WITH CHECK ADD  CONSTRAINT [FK_TBOPERACAO_TBTIPOTERMINAL] FOREIGN KEY([CODTIPOTERMINAL])
REFERENCES [dbo].[TBTIPOTERMINAL] ([CODTIPOTERMINAL])
GO
ALTER TABLE [dbo].[TBOPERACAO] CHECK CONSTRAINT [FK_TBOPERACAO_TBTIPOTERMINAL]
GO
ALTER TABLE [dbo].[TBTERMINAL]  WITH CHECK ADD  CONSTRAINT [FK_TBTERMINAL_TBTIPOTERMINAL] FOREIGN KEY([IDTIPOTERMINAL])
REFERENCES [dbo].[TBTIPOTERMINAL] ([CODTIPOTERMINAL])
GO
ALTER TABLE [dbo].[TBTERMINAL] CHECK CONSTRAINT [FK_TBTERMINAL_TBTIPOTERMINAL]
GO
ALTER TABLE [dbo].[TBTERMINAL]  WITH CHECK ADD  CONSTRAINT [FK_TBTERMINAL_TBUNIDADEINSTITUICAO] FOREIGN KEY([IDUNIDADEINST])
REFERENCES [dbo].[TBUNIDADEINSTITUICAO] ([IDUNIDADEINST])
GO
ALTER TABLE [dbo].[TBTERMINAL] CHECK CONSTRAINT [FK_TBTERMINAL_TBUNIDADEINSTITUICAO]
GO
ALTER TABLE [dbo].[TBTERMINAL]  WITH CHECK ADD  CONSTRAINT [FK_TBTERMINAL_TBUSUARIO] FOREIGN KEY([IDUSUARIO])
REFERENCES [dbo].[TBUSUARIO] ([IDUSUARIO])
GO
ALTER TABLE [dbo].[TBTERMINAL] CHECK CONSTRAINT [FK_TBTERMINAL_TBUSUARIO]
GO
